### ISSUE TITLE
Client crashes on teleporting to another world

### ISSUE THREAD

**Issue by daboross** [sillerud/MCClientFramework#1]
I've made a kind of basic framework for command-line interaction that uses this library.

When teleporting the player to another world (using the /world command from essentials), this error occurs: http://sprunge.us/NbaO.

The `23:45:17 [INFO] §aSending message to localhost:25565:daboross` is when I have the client send `/world world_nether` to the server.

I am connecting with a fake authentication, creating a new AuthenticationResponse with a fake JSONObject. Code is at http://git.io/WqFZEQ. Though I'm not sure how the fake authentication would create this.

**Comment by sillerud** [comment]
This should hopefully fix this problem.
